PL/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PL.Models.Data;
using PL.Models.ViewModels;
using System.Security.Claims;
using PL.Models;
using System.Data.Entity;

namespace PL.Controllers
{
    public class SettingsController : Controller
    {
        AppDbContext db = new AppDbContext();
        
        public SettingsController()
        {
            try
            {
                if (User.Identity.IsAuthenticated != null)
                {
                    if (User.Identity.IsAuthenticated)
                    {
                        ViewBag.Privlage = (User.Identity as ClaimsIdentity).FindFirst(ClaimTypes.Role).Value;
                    }
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine("Error:'{0}'", ex.Message);
                ViewBag.Privlage = "0";
            }
        }
        // GET: Settings
        [AllowAnonymous]
        
        public ActionResult Index(string filter, string sft)
        {
            if (filter == null) filter = "all";
            if (sft == null) sft = "N";
            List<SettingsViewModel> settingsViewList = new List<SettingsViewModel>();
            List<SettingsViewModel> setViewList = new List<SettingsViewModel>();
            List<SettingsModel> setList = new List<SettingsModel>();
            try
            {
                setList = db.Settings.ToList();
            }
            catch(Exception ex)
            {
                Console.WriteLine("Error: '{0}'", ex.Message);
                settingsViewList = null;
            }
            
            foreach(SettingsModel s in setList)
            {
                SettingsViewModel newModel = new SettingsViewModel();
                newModel.SettingId = s.Id;
                newModel.Line = s.Line.Title;
                newModel.Line_id = s.Line.Id;
                newModel.Shift = s.Shift;
                newModel.State = s.Line.state.ToString();
                newModel.Efficiency = s.Efficiency.ToString() + "%";
                newModel.LedTime = s.Line.LedTime;
                newModel.Time = s.Line.Time;
                newModel.Product = s.Product.Name;
                newModel.Project = s.Product.Project.Title;
                newModel.Workers = s.Workers;

                settingsViewList.Add(newModel);
            }
            if(setList != null)
            {
                if(filter == "On")
                {
                   foreach(SettingsViewModel m in settingsViewList)
                    {
                        if(m.State == STATUS.ON.ToString())
                        {
                            if (sft == "N")
                            {
                                setViewList.Add(m);
                            }
                            else if (sft == "A")
                            {
                                if (m.Shift == "Shift A") setViewList.Add(m);
                            }
                            else if (sft == "B")
                            {
                                if (m.Shift == "Shift B") setViewList.Add(m);
                            }

                        }
                    }
                }
                else if(filter == "Off")
                {
                    foreach (SettingsViewModel m in settingsViewList)
                    {
                        if (m.State == STATUS.OFF.ToString())
                        {
                            if (sft == "N" )
                            {
                                setViewList.Add(m);
                            }
                            else if (sft == "A")
                            {
                                if (m.Shift == "Shift A") setViewList.Add(m);
                            }
                            else if(sft == "B")
                            {
                                if (m.Shift == "Shift B") setViewList.Add(m);
                            }
                        }
                    }
                }
                else if(filter == "StnBy")
                {
                    foreach (SettingsViewModel m in settingsViewList)
                    {
                        if (m.State == STATUS.STAND_BY.ToString())
                        {
                            if (sft == "N")
                            {
                                setViewList.Add(m);
                            }
                            else if (sft == "A")
                            {
                                if (m.Shift == "Shift A") setViewList.Add(m);
                            }
                            else if (sft == "B")
                            {
                                if (m.Shift == "Shift B") setViewList.Add(m);
                            }
                        }
                    }
                }
                else
                {
                    if (sft == "N")
                    {
                        setViewList = settingsViewList;
                    }
                    else if (sft == "A")
                    {
                        setViewList = settingsViewList.Where(x => x.Shift == "Shift A").ToList();
                    }
                    else if (sft == "B")
                    {
                        setViewList = settingsViewList.Where(x => x.Shift == "Shift B").ToList();
                    }
                }
            }
            List<int> Selected = new List<int>();


            ViewBag.Filt = filter;
            ViewBag.Shift = sft;
            ViewBag.Selected = Selected;
            ViewBag.Index = 0;
            ViewBag.Settings = setViewList;
            return View();

        }

        [AllowAnonymous]
        public ActionResult StartLine(int? id , string f , string s)
        {
            if (id != null)
            {
                LineModel line = db.Lines.Find(id);
                LineModel newLine = new LineModel();
                newLine.Id = line.Id;
                newLine.Device = line.Device;
                newLine.Enabled = line.Enabled;
                newLine.LedTime = line.LedTime;
                newLine.Set_state = STATUS.ON;
                newLine.state = line.state;
                newLine.Time = line.Time;
                newLine.Title = line.Title;
                line.state = STATUS.STAND_BY;
                line.Set_state = STATUS.ON;
                db.Entry(line).State = EntityState.Modified;
                try { db.SaveChanges(); }
                catch (Exception ex)
                {
                    Console.WriteLine("Error:'{0}'", ex.Message);
                }
                
            }
            return RedirectToAction("Index", new { filter = f, sft = s });
        }

        [AllowAnonymous]
        public ActionResult StopLine(int? id, string f, string s)
        {
            LineModel line = db.Lines.Find(id);
            LineModel newLine = new LineModel();
            newLine.Id = line.Id;
            newLine.Device = line.Device;
            newLine.Enabled = line.Enabled;
            newLine.LedTime = line.LedTime;
            newLine.Set_state = STATUS.OFF;
            newLine.state = line.state;
            newLine.Time = line.Time;
            newLine.Title = line.Title;
            line.state = STATUS.OFF;
            line.Set_state = STATUS.OFF;
            db.Entry(line).State = EntityState.Modified;
            try { db.SaveChanges(); }
            catch (Exception ex)
            {
                Console.WriteLine("Error:'{0}'", ex.Message);
            }
            return RedirectToAction("Index", new { filter = f, sft = s });
        }

        private TimeSpan GetTimeOfLine(ProjectModel project)
        {
            TimeSpan time = new TimeSpan();
            List<ProductsModel> Products = db.Products.Where(x => x.Project.Id == project.Id).ToList();
            foreach(ProductsModel product in Products)
            {
                time = time + product.Time;
            }
            


            return time;
        }

        [Authorize(Roles = "User, Supervisor, Admin, Root")]
        [HttpGet]
        public ActionResult AddSettings()
        {
            List<string> items = new List<string>();
            List<ProjectModel> Projects = db.Projects.ToList();
            if (Projects.Count != 0)
            {
                foreach (ProjectModel model in Projects)
                {

                    items.Add(model.Title.ToString());
                }
            }
            ViewBag.ProjectDropdown = items;
            return View();
        }

        [Authorize(Roles = "User, Supervisor, Admin, Root")]
        [HttpPost]
        public ActionResult AddSettings(SettingsViewModel model)
        {
            return View();
        }

        public bool CheckChBoxes()
        {
            if(ViewBag.Selected.Count() == 0)
            {
                return false;
            }
            else
            {
                return true;
            }
        }


       [HttpGet]
        [AllowAnonymous]
        public ActionResult ManageLines()
        {
            List<SettingsViewModel> settingsViewList;
            var m = new SettingsViewModel();
            try
            {
                settingsViewList = db.Settings.ToArray().OrderBy(x => x.Line.Id).Select(x => new SettingsViewModel(x)).ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: '{0}'", ex.Message);
                settingsViewList = null;
            }

            List<ProductsModel> produkty = new List<ProductsModel>();
            List<LineModel> linky = new List<LineModel>();
            try
            {
                produkty = db.Products.ToList();
                linky = db.Lines.ToList();
            }
            catch (Exception ex)
            {

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Production Light Control System</title>
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    @System.Web.Optimization.Styles.Render("~/Content/materialize")
    @System.Web.Optimization.Styles.Render("~/Content/font")
    @System.Web.Optimization.Styles.Render("~/Content/main")
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/materialize")
    @System.Web.Optimization.Scripts.Render("~/bundles/main")

    <script type="text/javascript">
        function load() {
            setInterval(function () {
                window.location.reload();
            }, 150000);
        }
    </script>
</head>
<body onload="load()">
<header>
        <nav class="top-nav z-depth-2">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @{
                        string Tit = ViewBag.Title;
                    }
                    @Html.ActionLink(Tit, "Index", "Settings", new { area = "" }, new { @class = "navbar-brand" })*@

                <div class="container">
                    <div class="nav-wrapper">
                        <div class="table">
                            <div class="tableCell">
                                <h1>Production Light<br> Control System</h1>
                            </div>
                        </div>
                    </div>
                    <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only">
                        <div class="table">
                            <div class="tableCell">
                                <i class="large material-icons">toc</i>
                            </div>
                        </div>
                    </a>

                </div>

               
        </nav>

        <ul id="nav-mobile" class="side-nav fixed">
            <li id="logo" class="z-depth-3">
                <div class="userView">
                    <div class="table">
                        <div class="tableCell">
                            <img style="height: 6em; width: 6em" src="~/images/PTS_LOGO.png">
                        </div>
                    </div>

                </div>
            </li>


            <li class="search">
                <div class="search-wrapper card">
                    <input id="search">
                    <i class="material-icons">search</i>

                    <div class="search-results"></div>
                </div>
            </li>
            @Html.Partial("_LoginPartial")
            <hr>
            <i class="material-icons fontIcon" id="plusFont">zoom_in</i>
            <i class="material-icons fontIcon" id="minusFont">zoom_out</i>
        </ul>

    </header>

        @RenderBody()
        
    
    @*<footer>
        <div id="footerContainer">
            <p>&copy; @DateTime.Now.Year - AUTSYSautomation</p>
        </div>
    </footer>
   *@
</body>

</html>

PL/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Production Light Control System</title>
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

    <meta name="description" content="The description of my page" />
</head>
<body>

    @RenderBody()

    <!--
        <footer style="position:fixed;bottom:0px;z-index:100;width:100%;height:3em;background-color:#CCCBCB;line-height:1.5em;">
        <p style="padding:0;margin:0;text-align:center">Production Lights Control system by AUTSYS automation<br /> &copy; @DateTime.Now.Year - All rights reserved</p>
    </!--footer>
     -->
</body>
</html>